main: org.makershaven.claimfly.ClaimFly
api-version: "1.18"
version: "${project.version}"
name: "ClaimFly"
author: "Weaves"
depend: [GriefPrevention, Vault]
description: Allows flight in GriefPrevention claims!
commands:
  claimfly:
    aliases: cfly
    description: ClaimFly main command!
    permission: claimfly.command
    usage: /<command> args
permissions:
  claimfly.*:
    description: Allows all permissions.
    default: op
    children:
      claimfly.commands.admin: true
      claimfly.use: true
      claimfly.command: true
      claimfly.claims.others: true
      claimfly.claims.admin: true
      claimfly.claims.unclaimed: true
  claimfly.use:
    description: Allows flight in your own claim.
    default: false
  claimfly.command:
    description: Allows you to toggle flight with /claimfly
    default: false
  claimfly.commands.admin:
    description: Allows you to do the admin commands.
    default: false
  claimfly.commands.boundary.toggle:
    description: Allows you to toggle the boundary on or off with /claimfly boundary.
    default: false
  claimfly.commands.boundary.set:
    description: Allows you to set you boundary show distance with /claimfly boundary <number>.
  claimfly.claims.others:
    description: Allows you to fly in other peoples claims.
    default: false
  claimfly.claims.admin:
    description: Allows you to fly in admin claims.
    default: false
    children:
      claimfly.command: true
  claimfly.claims.unclaimed:
    description: Allows you to fly in unclaimed land.
    default: false
